apiVersion: v1
kind: Service
metadata:
  name: external-read-postgres
  namespace: event-sourcing-demo
spec:
  type: ExternalName
  externalName: host.rancher-desktop.internal
  ports:
    - name: postgres
      port: 5433
      targetPort: 5433
