apiVersion: v1
kind: Secret
metadata:
  name: task-db-secret
  namespace: event-sourcing-demo
type: Opaque
stringData:
  username: tasks
  password: tasks
  event_store_database_url: postgresql://tasks:tasks@external-event-postgres:5432/task_events
  read_store_database_url: postgresql://tasks:tasks@external-read-postgres:5433/task_read
