apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: migrations-demo
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migrator
  namespace: migrations-demo
automountServiceAccountToken: false

