apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app
  namespace: demo
  labels:
    app.kubernetes.io/name: python-postgres-demo
    app.kubernetes.io/part-of: vault-postgres-security-demo
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-migrate
  namespace: demo
  labels:
    app.kubernetes.io/name: python-postgres-demo
    app.kubernetes.io/component: migration
    app.kubernetes.io/part-of: vault-postgres-security-demo
automountServiceAccountToken: true
