apiVersion: v1
kind: Pod
metadata:
  name: vault-injector-smoke
  namespace: demo
  labels:
    app.kubernetes.io/name: vault-injector-smoke
    app.kubernetes.io/part-of: vault-postgres-security-demo
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "demo-app"
    vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/demo-app-runtime"
    vault.hashicorp.com/agent-inject-template-db-creds: |
      {{- with secret "database/creds/demo-app-runtime" -}}
      DB_USERNAME={{ .Data.username }}
      DB_PASSWORD={{ .Data.password }}
      {{- end }}
    vault.hashicorp.com/agent-inject-perms-db-creds: "0400"
spec:
  serviceAccountName: demo-app
  restartPolicy: Never
  containers:
    - name: app
      image: hashicorp/vault:1.17.6
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -ec
        - sleep 3600

