apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: vault-postgres-security-demo
spec:
  secretName: vault-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
  dnsNames:
    - vault
    - vault.vault
    - vault.vault.svc
    - vault.vault.svc.cluster.local
  issuerRef:
    name: demo-ca
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-tls
  namespace: database
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: vault-postgres-security-demo
spec:
  secretName: postgres-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
  dnsNames:
    - host.rancher-desktop.internal
    - localhost
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: demo-ca
    kind: ClusterIssuer
    group: cert-manager.io
