apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: rabbitmq-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: rabbitmq-demo-subscriber:demo
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: external-postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: taskdb
            - name: POSTGRES_USER
              value: tasks
            - name: POSTGRES_PASSWORD
              value: tasks
            - name: RABBITMQ_HOST
              value: external-rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: tasks
            - name: RABBITMQ_PASSWORD
              value: tasks
            - name: RABBITMQ_EXCHANGE
              value: integration.events
            - name: RABBITMQ_QUEUE
              value: task.subscriber
            - name: RABBITMQ_BINDING_KEY
              value: task.*
          startupProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 10
