apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: grafana-lgtm-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: smtp
              containerPort: 1025
            - name: http
              containerPort: 8025
          readinessProbe:
            httpGet:
              path: /
              port: 8025
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8025
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: grafana-lgtm-demo
spec:
  selector:
    app: mailhog
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: http
      port: 8025
      targetPort: 8025
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailhog
  namespace: grafana-lgtm-demo
spec:
  ingressClassName: traefik
  rules:
    - host: mailhog.grafana-lgtm.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mailhog
                port:
                  number: 8025
