mode: standalone
replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

rootUser: admin
rootPassword: alarik123

persistence:
  enabled: true
  size: 5Gi

service:
  type: ClusterIP
  port: 9000

consoleService:
  type: ClusterIP
  port: 9001
