apiVersion: v1
kind: Secret
metadata:
  name: registry-db-secret
  namespace: registry-poc
type: Opaque
stringData:
  username: registry
  password: registry
  event_store_database_url: postgresql://registry:registry@external-event-postgres:5432/registry_events
  read_store_database_url: postgresql://registry:registry@external-read-postgres:5433/registry_read
