apiVersion: v1
kind: Service
metadata:
  name: registry-python-app
  namespace: registry-poc
spec:
  type: ClusterIP
  selector:
    app: registry-python-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
