apiVersion: v1
kind: Service
metadata:
  name: openbao-demo-app
  namespace: openbao-demo
spec:
  selector:
    app: openbao-demo-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
