CREATE DATABASE appdb;

\connect appdb

CREATE ROLE app_user LOGIN PASSWORD 'app_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE migrator_user LOGIN PASSWORD 'migrator_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON DATABASE appdb FROM PUBLIC;

CREATE SCHEMA app AUTHORIZATION postgres;

GRANT CONNECT ON DATABASE appdb TO app_user;
GRANT CONNECT ON DATABASE appdb TO migrator_user;

GRANT USAGE ON SCHEMA app TO app_user;
GRANT USAGE, CREATE ON SCHEMA app TO migrator_user;

ALTER DEFAULT PRIVILEGES FOR ROLE migrator_user IN SCHEMA app
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrator_user IN SCHEMA app
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app_user;
