apiVersion: v1
kind: Service
metadata:
  name: external-redis
  namespace: redis-demo
spec:
  type: ExternalName
  externalName: host.rancher-desktop.internal
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
